{{- if .Values.config.caCerts }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "release-listener.fullname" . }}-certs
  labels:
    {{- include "release-listener.labels" . | nindent 4 }}
data:
  ca_bundle.pem: |
    {{- .Values.config.caCerts | nindent 4 }}
{{- end }}
