{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "release-listener.fullname" . }}
  labels:
    {{- include "release-listener.labels" . | nindent 4 }}
type: Opaque
data:
  sonatype-username: {{ .Values.secrets.sonatypeUsername | b64enc | quote }}
  sonatype-password: {{ .Values.secrets.sonatypePassword | b64enc | quote }}
  {{- if .Values.falkordb.password }}
  falkordb-password: {{ .Values.falkordb.password | b64enc | quote }}
  {{- end }}
{{- end }}
