{{- if and .Values.sbomGraphApi.enabled (eq (.Values.sbomGraphApi.secrets.delivery | default "env") "awsSecretsManagerCsi") .Values.sbomGraphApi.secrets.awsSecretsManagerCsi.secretProviderSpec }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "sbom-graph.sbomGraphApi.awsSecretProviderClassName" . }}
  labels:
    {{- include "sbom-graph.sbomGraphApi.labels" . | nindent 4 }}
spec:
{{- toYaml .Values.sbomGraphApi.secrets.awsSecretsManagerCsi.secretProviderSpec | nindent 2 }}
{{- end }}
