{{- if and .Values.sbomGraphApi.enabled .Values.sbomGraphApi.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sbom-graph.sbomGraphApi.serviceAccountName" . }}
  labels:
    {{- include "sbom-graph.sbomGraphApi.labels" . | nindent 4 }}
  {{- if .Values.sbomGraphApi.serviceAccount.irsaRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.sbomGraphApi.serviceAccount.irsaRoleArn | quote }}
  {{- end }}
{{- end }}
