{{- if and .Values.enrichment.trustScore.enabled .Values.enrichment.trustScore.ossindex.user }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sbom-graph.fullname" . }}-ossindex
  labels:
    {{- include "sbom-graph.labels" . | nindent 4 }}
type: Opaque
data:
  OSSINDEX_USER: {{ .Values.enrichment.trustScore.ossindex.user | b64enc | quote }}
  OSSINDEX_TOKEN: {{ .Values.enrichment.trustScore.ossindex.token | b64enc | quote }}
{{- end }}
