apiVersion: v2
name: sbom-graph-api
description: A Helm chart for SBOM Graph API - Flask application for FalkorDB graph data visualizations
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - sbom
  - data-visualization
  - falkordb
  - graph
  - flask
maintainers:
  - name: Brett Crawley
